const SUPABASE_URL = 'https://nijsfyysxvqogjjfawrc.supabase.co';
const SUPABASE_KEY = 'sb_publishable_YBMEKwWJCtTZsiRBS45hGQ_sDogz1SE';
const sb = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

const SERVIZI_SGROVIO = ['Sgomberi e traslochi','Giardinaggio','Idraulico','Elettricista','Fabbro','Muratore','Imbianchino','Manutenzione caldaie/climatizzatori','Pulizie','Tinteggiatura','Piccoli lavori','Altro'];
function aggiornaMenuServizi(){document.querySelectorAll('select[name="Servizio"]').forEach(s=>{const v=s.value;s.innerHTML='<option value="">Seleziona</option>'+SERVIZI_SGROVIO.map(x=>`<option>${x}</option>`).join('');if(SERVIZI_SGROVIO.includes(v))s.value=v;});} aggiornaMenuServizi();

function aggiungiAccessi(){const nav=document.querySelector('.nav');const navPro=nav?.querySelector('.navlink');if(nav&&navPro){navPro.textContent='Area Professionista';navPro.href='professionista.html';}const actions=document.querySelector('.hero .actions');if(actions&&!actions.querySelector('a[href="cliente.html"]')){const a=document.createElement('a');a.className='btn secondary';a.href='cliente.html';a.textContent='Area Cliente';actions.appendChild(a);}if(actions&&!actions.querySelector('a[href="professionista.html"]')){const a=document.createElement('a');a.className='btn secondary';a.href='professionista.html';a.textContent='Area Professionista';actions.appendChild(a);}}
aggiungiAccessi();

function value(fd,n){const v=fd.get(n);return typeof v==='string'?v.trim():'';}
function parseRaggio(raw){const m=String(raw||'').match(/\d+/);return m?Number(m[0]):20;}
function showResult(id,msg,ok=true){const b=document.getElementById(id);if(!b)return;b.style.display='block';b.innerHTML=ok?`<b>✓ ${msg}</b>`:`<b>Invio non riuscito.</b><br>${msg}`;b.scrollIntoView({behavior:'smooth',block:'center'});}
function setBusy(f,b,label='Invio…'){const x=f.querySelector('button[type="submit"]');if(!x)return;if(!x.dataset.label)x.dataset.label=x.textContent;x.disabled=b;x.textContent=b?label:x.dataset.label;}
async function signup(email,password){const {data,error}=await sb.auth.signUp({email,password});if(error)throw error;if(!data.user)throw new Error('Account non creato');return data.user;}

const clientForm=document.querySelector('#richiesta form.formgrid');
const proForm=document.querySelector('#professionisti form.formgrid');

if(clientForm&&!clientForm.querySelector('[name="Password_cliente"]')){const check=clientForm.querySelector('.check');const row=document.createElement('div');row.className='row';row.innerHTML=`<label>Password Area Cliente<input type="password" name="Password_cliente" minlength="8" required autocomplete="new-password" placeholder="Minimo 8 caratteri"></label><label>Conferma password<input type="password" name="Conferma_cliente" minlength="8" required autocomplete="new-password" placeholder="Ripeti la password"></label>`;clientForm.insertBefore(row,check);const note=document.createElement('div');note.className='small';note.textContent='Con email e password potrai seguire questa richiesta dalla tua Area Cliente.';clientForm.insertBefore(note,check);}

if(clientForm){clientForm.addEventListener('submit',async e=>{e.preventDefault();if(!clientForm.reportValidity())return;const fd=new FormData(clientForm),email=value(fd,'email').toLowerCase(),pw=value(fd,'Password_cliente'),pw2=value(fd,'Conferma_cliente');if(!email){showResult('okC','Inserisci un indirizzo email: servirà per il tuo account cliente.',false);return;}if(pw!==pw2){showResult('okC','Le due password non coincidono.',false);return;}setBusy(clientForm,true,'Creazione richiesta…');try{let {data:{user}}=await sb.auth.getUser();if(!user)user=await signup(email,pw);const {error}=await sb.from('richieste').insert({user_id:user.id,nome_cliente:value(fd,'Nome'),email,telefono:value(fd,'Telefono')||null,categoria:value(fd,'Servizio'),descrizione:value(fd,'Descrizione'),comune:value(fd,'Comune')||null,cap:value(fd,'CAP'),provincia:'MN',budget:value(fd,'Budget')||null,urgenza:value(fd,'Tempistica'),stato:'nuova'});if(error)throw error;clientForm.reset();showResult('okC','Richiesta salvata e collegata al tuo account. Puoi seguirla dall’Area Cliente.');}catch(err){const m=String(err.message||err);showResult('okC',m.toLowerCase().includes('already')?'Questa email ha già un account. Accedi prima dall’Area Cliente, poi torna qui per una nuova richiesta.':m,false);}finally{setBusy(clientForm,false);}});}

if(proForm&&!proForm.querySelector('[name="Password"]')){const check=proForm.querySelector('.check');const row=document.createElement('div');row.className='row';row.innerHTML=`<label>Password per Area Professionista<input type="password" name="Password" minlength="8" autocomplete="new-password" required placeholder="Minimo 8 caratteri"></label><label>Conferma password<input type="password" name="Conferma_password" minlength="8" autocomplete="new-password" required placeholder="Ripeti la password"></label>`;proForm.insertBefore(row,check);}
if(proForm){proForm.addEventListener('submit',async e=>{e.preventDefault();if(!proForm.reportValidity())return;const fd=new FormData(proForm),pw=value(fd,'Password'),pw2=value(fd,'Conferma_password'),email=value(fd,'email').toLowerCase();if(pw!==pw2){showResult('okP','Le due password non coincidono.',false);return;}setBusy(proForm,true,'Creazione account…');try{const user=await signup(email,pw);const {error}=await sb.from('professionisti').insert({nome:value(fd,'Nome_attivita'),email,telefono:value(fd,'Telefono')||null,attivita:value(fd,'Nome_attivita'),categoria:value(fd,'Servizio'),comune:value(fd,'Zone_servite'),provincia:'MN',raggio_km:parseRaggio(value(fd,'Raggio_massimo')),disponibile:true,verificato:false,stato:'in_attesa',user_id:user.id});if(error)throw error;proForm.reset();showResult('okP','Candidatura e account creati. Ora puoi accedere all’Area Professionista.');}catch(err){showResult('okP',String(err.message||err),false);}finally{setBusy(proForm,false);}});}
